name: qa deploy
on:
  repository_dispatch:
    types: [qa-deploy-command]

jobs:
  qa-deploy-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Check for changes in migrations
        run: |
          changed_files=$(gh pr diff --name-only)
          if echo "$changed_files" | grep -q '^src/migrations/'; then
            echo "Changes detected in migrations. Exiting workflow."
            # exit 1  # Exit with failure status
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Set Version
        id: set-version
        run: |
          echo "version=qa-${{ steps.pr.outputs.pull_request_number }}" >> $GITHUB_OUTPUT
  
      - name: Set short git commit SHA
        id: commit-sha
        uses: prompt/actions-commit-hash@v2

      - name: Print version
        run: |
          echo "Version set: ${{ steps.set-version.outputs.version }}"

      - name: Print commit SHA
        run: |
          echo "Commit SHA: ${{ steps.commit-sha.outputs.hash }}"