name: qa deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print pull_request object
        run: echo "${{ toJson(github.event.client_payload.pull_request) }}"

      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0

      - name: echo text for deploy
        run: |
          echo "This is qa-deploy"
          cat read.txt
