name: Deploy QA Environment

on:
  workflow_dispatch:
    inputs:
      pull_request_url:
        description: 'URL of the pull request to identify which QA environment should be deployed.'
        required: true
      comment_id:
        description: 'ID of the comment to add reactions to.'
        required: true
  pull_request:
    types: [closed]     

permissions:
  issues: write
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Switch to PR's branch
        id: checkout_branch
        run: |
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add-success-reaction:
    needs: check-migrations
    runs-on: ubuntu-latest
    if: github.event.inputs.comment_id
    steps:
      - name: Add success reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: hooray

  add-failure-reaction:
    needs: check-migrations
    if: failure() && github.event.inputs.comment_id
    runs-on: ubuntu-latest
    steps:
      - name: Add failure reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: -1
