name: qa deploy
on:
  workflow_dispatch:
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Check for changes in migration files
        id: check_changes
        run: |
          git fetch --all
          base_commit=$(jq -r .pull_request.base.sha $GITHUB_EVENT_PATH)
          current_commit=$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)
          git diff --name-only $base_commit $current_commit > changed_files.txt
          cat changed_files.txt