name: Deploy QA Environment

on:
  workflow_dispatch:
    inputs:
      pull_request_url:
        description: 'URL of the pull request to identify which QA environment should be deployed.'
        required: true
      comment_id:
        description: 'ID of the comment to add reactions to.'
        required: true
  pull_request:
    types: [closed]     

permissions:
  issues: write
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit SHA from PR
        id: get_commit_sha
        run: |
          PR_URL="${{ github.event.inputs.pull_request_url || github.event.pull_request.url }}"
          PR_NUMBER=$(echo "$PR_URL" | awk -F '/' '{print $NF}')
          COMMIT_SHA=$(gh pr view $PR_NUMBER --json commits -q '.commits[-1].oid')
          echo "pull_request_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print PR number and commit SHA
        run: |
          echo "Pull request number: ${{ steps.get_commit_sha.outputs.pull_request_number }}"
          echo "Commit SHA: ${{ steps.get_commit_sha.outputs.commit_sha }}"

  add-success-reaction:
    needs: check-migrations
    runs-on: ubuntu-latest
    if: github.event.inputs.comment_id
    steps:
      - name: Add success reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: hooray

  add-failure-reaction:
    needs: check-migrations
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Add failure reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: -1
