name: qa deploy
on:
  workflow_dispatch:
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Check for changes in migrations
        run: |
          changed_files=$(gh pr diff --name-only)
          if echo "$changed_files" | grep -q '^src/migrations/'; then
            echo "Changes detected in migrations. Exiting workflow."
            exit 1  # Exit with failure status
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      
      - name: echo next
        run: echo "This is next"
