name: lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  check-go-files:
    name: Check if .go files were modified
    runs-on: ubuntu-latest
    outputs:
      go_files_modified: ${{ steps.check-go-files.outputs.go_files_modified }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for modified .go files
        id: check-go-files
        run: |
          git fetch --all
          base_commit=$(jq -r .pull_request.base.sha $GITHUB_EVENT_PATH)
          current_commit=$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)
          if git diff --name-only $base_commit $current_commit | grep '\.go$'; then
            echo "Go files modified."
            echo "go_files_modified=true" >> $GITHUB_OUTPUT
          else
            echo "No Go files modified."
            echo "go_files_modified=false" >> $GITHUB_OUTPUT
          fi

  lint:
    name: Run Lint if .go files were modified
    runs-on: ubuntu-latest
    needs: check-go-files
    if: needs.check-go-files.outputs.go_files_modified == 'true'
    steps:
      - name: Configure git to use GH_TOKEN
        run: |
          git config --global url."https://${{ secrets.PAT }}:@github.com/".insteadOf "https://github.com/"
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.6

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
