name: qa deploy
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      event:
        description: 'The event of slash command'
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Check for changes in migrations
        run: |
          echo ${{inputs.comment-id}}
          echo ${{inputs.repository}}
          echo ${{toJson(inputs.event)}}
      
      - name: echo next
        run: cat read.txt
