name: qa deploy
on:
  workflow_dispatch:
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get GitHub Pull Request Information
        id: pr
        run: |
          pr_data=$(gh pr view --json baseRefName,headRefName,author,body,comments,state,number,labels,commits,createdAt,updatedAt)
          echo "pull_request=$pr_data" >> $GITHUB_OUTPUT
          echo "$pr_data"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Get base and head commit SHA
        id: pr-commits
        run: |
          base_commit=$(gh pr view --json baseRefOid -q '.baseRefOid')
          head_commit=$(gh pr view --json headRefOid -q '.headRefOid')
          echo "base_commit=$base_commit" >> $GITHUB_OUTPUT
          echo "head_commit=$head_commit" >> $GITHUB_OUTPUT
          echo "Base commit: $base_commit"
          echo "Head commit: $head_commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
