name: qa deploy
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL of the PR'
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      
      - name: Extract branch name from PR URL
        id: extract_branch
        run: |
          echo "PR_URL=${{ github.event.inputs.url }}" # Log the PR URL for debugging
          # Extract the branch name from the URL
          BRANCH_NAME=$(echo "${{ github.event.inputs.url }}" | sed -E 's#.*/([^/]+)/([^/]+)#\2#') # Adjust according to your URL structure
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV # Set the branch name as an environment variable

      - name: Checkout to the branch
        run: |
          echo "Checking out branch: $BRANCH_NAME"
          git checkout "$BRANCH_NAME"

      - name: Echo next
        run: cat read.txt
