name: Deploy QA Environment

on:
  workflow_dispatch:
    inputs:
      pull_request_url:
        description: 'URL of the pull request for identifying for which QA environment should be deployed.'
        required: true
      comment_id:
        description: 'URL of the pull request for identifying for which QA environment should be deployed.'
        required: true

permissions:
  issues: write
  id-token: write
  contents: read
  pull-requests: write


jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Switch to PR's branch
      id: checkout_branch
      run: |
        PR_URL="${{ github.event.inputs.pull_request_url }}"
        PR_NUMBER=$(echo "$PR_URL" | awk -F '/' '{print $NF}')
        BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
        echo "pull_request_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        git checkout $BRANCH_NAME
        exit 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add-reaction:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: hooray