name: lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Configure git to use GH_TOKEN
        run: |
          git config --global url."https://${{ secrets.PAT }}:@github.com/".insteadOf "https://github.com/"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - uses: actions/checkout@v4

      - name: Check if .go files were modified
        id: check-go-files
        run: |
          if ! git diff --name-only HEAD~1 -- . | grep '\.go$'; then
            exit 0;
            echo "No Go files modified."
          fi

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.6
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
