name: qa deploy
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL of the PR'
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Get branch name from PR URL
        id: get_branch
        run: |
          PR_NUMBER=$(echo "${{ github.event.inputs.url }}" | awk -F '/' '{print $NF}')
          BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo next
        run: cat read.txt
