name: qa deploy
on:
  workflow_dispatch:
permissions:
  pull-requests: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout pull request
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.PAT }}
      #     fetch-depth: 0

      - name: Print input object
        run: echo ${{toJson(inputs)}}

      - name: Print context.issue.number
        run: echo context.issue.number
          
      - uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              echo "Return issue number if present"
              return context.issue.number;
            } else {
              echo "Otherwise return issue number from commit"
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Issue number
        run: echo '${{steps.get_issue_number.outputs.result}}'