name: qa deploy
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL of the PR'
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name from PR URL
        id: get_branch
        run: |
          PR_NUMBER=$(echo "${{ github.event.inputs.url }}" | awk -F '/' '{print $NF}')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          BRANCH_NAME=$(echo "$PR_DATA" | jq -r '.head.ref')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV # Set the branch name as an environment variable

      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: $BRANCH_NAME
  
      # - name: Checkout to the branch
      #   run: |
      #     echo "Checking out branch: $BRANCH_NAME"
      #     git checkout "$BRANCH_NAME"

      - name: Echo next
        run: cat read.txt
