name: Deploy QA Environment

on:
  workflow_dispatch:
    inputs:
      pull_request_url:
        description: 'URL of the pull request to identify which QA environment should be deployed.'
        required: true
      comment_id:
        description: 'ID of the comment to add reactions to.'
        required: true
  pull_request:
    types: [closed]     

permissions:
  issues: write
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to PR's branch
        id: checkout_branch
        run: |
          PR_URL="${{ github.event.inputs.pull_request_url }}"
          PR_NUMBER=$(echo "$PR_URL" | awk -F '/' '{print $NF}')
          BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
          echo "pull_request_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git checkout $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add-success-reaction:
    needs: check-migrations
    if: success() && github.event.inputs.comment_id
    runs-on: ubuntu-latest
    steps:
      - name: Add success reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: hooray

  add-failure-reaction:
    needs: check-migrations
    if: failure() && github.event.inputs.comment_id
    runs-on: ubuntu-latest
    steps:
      - name: Add failure reaction to the comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment_id }}
          reactions: -1
