name: qa deploy
on:
  workflow_dispatch:
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get list of changed files
        id: changed-files
        run: |
          changed_files=$(gh pr diff --name-only)
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
          echo "Changed files:"
          echo "$changed_files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
